### ISSUE TITLE
centos-install.sh script failed

### ISSUE THREAD

**Issue by SitWatchCloudRise** [gisjedi/ixgbevf#1]
Hello,
I got the error when use your script to build our ami. below are output message:

```
    amazon-ebs:
    amazon-ebs: Complete!
    amazon-ebs: ixgbevf-3.2.2/
    amazon-ebs: ixgbevf-3.2.2/scripts/
    amazon-ebs: ixgbevf-3.2.2/scripts/set_irq_affinity
    amazon-ebs: ixgbevf-3.2.2/SUMS
    amazon-ebs: ixgbevf-3.2.2/ixgbevf.spec
    amazon-ebs: ixgbevf-3.2.2/COPYING
    amazon-ebs: ixgbevf-3.2.2/src/
    amazon-ebs: ixgbevf-3.2.2/src/kcompat.c
    amazon-ebs: ixgbevf-3.2.2/src/common.mk
    amazon-ebs: ixgbevf-3.2.2/src/Makefile
    amazon-ebs: ixgbevf-3.2.2/src/ixgbe_vf.h
    amazon-ebs: ixgbevf-3.2.2/src/kcompat.h
    amazon-ebs: ixgbevf-3.2.2/src/ixgbe_common.h
    amazon-ebs: ixgbevf-3.2.2/src/ixgbevf_ethtool.c
    amazon-ebs: ixgbevf-3.2.2/src/ixgbe_mbx.c
    amazon-ebs: ixgbevf-3.2.2/src/ixgbevf_osdep2.h
    amazon-ebs: ixgbevf-3.2.2/src/ixgbe_type.h
    amazon-ebs: ixgbevf-3.2.2/src/kcompat_ethtool.c
    amazon-ebs: ixgbevf-3.2.2/src/ixgbevf_main.c
    amazon-ebs: ixgbevf-3.2.2/src/ixgbe_vf.c
    amazon-ebs: ixgbevf-3.2.2/src/ixgbe_mbx.h
    amazon-ebs: ixgbevf-3.2.2/src/ixgbevf_osdep.h
    amazon-ebs: ixgbevf-3.2.2/src/ixgbevf_param.c
    amazon-ebs: ixgbevf-3.2.2/src/Module.supported
    amazon-ebs: ixgbevf-3.2.2/src/ixgbevf.h
    amazon-ebs: ixgbevf-3.2.2/ixgbevf.7
    amazon-ebs: ixgbevf-3.2.2/pci.updates
    amazon-ebs: ixgbevf-3.2.2/README
    amazon-ebs:
    amazon-ebs: Creating symlink /var/lib/dkms/ixgbevf/3.2.2/source ->
    amazon-ebs: /usr/src/ixgbevf-3.2.2
    amazon-ebs:
    amazon-ebs: DKMS: add completed.
    amazon-ebs:
    amazon-ebs: Kernel preparation unnecessary for this kernel.  Skipping...
    amazon-ebs:
    amazon-ebs: Building module:
    amazon-ebs: cleaning build area...
    amazon-ebs: cd src/; make BUILD_KERNEL=3.10.0-514.26.2.el7.x86_64...(bad exit status: 2)
    amazon-ebs: Error! Bad return status for module build on kernel: 3.10.0-514.26.2.el7.x86_64 (x86_64)
    amazon-ebs: Consult /var/lib/dkms/ixgbevf/3.2.2/build/make.log for more information.
    amazon-ebs:
    amazon-ebs: Kernel preparation unnecessary for this kernel.  Skipping...
    amazon-ebs:
    amazon-ebs: Building module:
    amazon-ebs: cleaning build area...
    amazon-ebs: cd src/; make BUILD_KERNEL=3.10.0-514.26.2.el7.x86_64...(bad exit status: 2)
    amazon-ebs: Error! Bad return status for module build on kernel: 3.10.0-514.26.2.el7.x86_64 (x86_64)
    amazon-ebs: Consult /var/lib/dkms/ixgbevf/3.2.2/build/make.log for more information.
    amazon-ebs: Generating grub configuration file ...
    amazon-ebs: Found linux image: /boot/vmlinuz-3.10.0-514.26.2.el7.x86_64
    amazon-ebs: Found initrd image: /boot/initramfs-3.10.0-514.26.2.el7.x86_64.img
    amazon-ebs: Found linux image: /boot/vmlinuz-3.10.0-327.10.1.el7.x86_64
    amazon-ebs: Found initrd image: /boot/initramfs-3.10.0-327.10.1.el7.x86_64.img
    amazon-ebs: Found linux image: /boot/vmlinuz-0-rescue-f32e0af35637b5dfcbedcb0a1de8dca1
    amazon-ebs: Found initrd image: /boot/initramfs-0-rescue-f32e0af35637b5dfcbedcb0a1de8dca1.img
    amazon-ebs: done
```

It has the same error if the centos-install.sh is run manually on a centos instance. do you have any clue about that?
Regards,
